chore(workflow): split ci workflow in multiple workflows & fix regex (#1501)

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,4 +1,4 @@
-name: ci
+name: check
 
 on:
   push:
@@ -17,13 +17,21 @@ concurrency:
 jobs:
   version:
     name: Ensure package version match
-    if: startsWith(github.ref, 'refs/tags/v')
+    if: startsWith(github.ref_name, 'v')
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
+      - name: Check Git tag format
+        run: |
+          _tag="${{ github.ref_name }}"
+          if ! printf "%s\n" "$_tag" | grep -q -P '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$'; then
+            printf '[ERROR]: Git tag (%s) wrong format\n' "$_tag"
+            exit 1
+          fi
 
       - name: Read package.json version
         uses: sergeysova/jq-action@v2
@@ -82,7 +90,7 @@ jobs:
           fi
 
   check:
-    name: Build & Lint & Tests
+    name: Build & Lint & Test
     needs: version
     if: always() && (needs.version.result == 'success' || needs.version.result == 'skipped')
     runs-on: ubuntu-latest
@@ -124,116 +132,3 @@ jobs:
       - name: Upload code coverage
         uses: codecov/codecov-action@v3
         if: matrix.node-version == '18.x'
-
-  release:
-    name: Release package on NPM
-    needs: check
-    if: needs.check.result == 'success' && startsWith(github.ref, 'refs/tags/v')
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-      id-token: write
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Read package.json version
-        uses: sergeysova/jq-action@v2
-        id: version
-        with:
-          cmd: jq --raw-output .version package.json
-
-      - name: Determine if version is prerelease
-        id: prerelease
-        run: |
-          _prerelease=
-          if printf "%s\n" "${{ steps.version.outputs.value }}" | grep -q -P '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'; then
-            _prerelease=false
-          else
-            _prerelease=true
-          fi
-
-          printf 'value=%s\n' "$_prerelease" >> "$GITHUB_OUTPUT"
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "18.x"
-          registry-url: "https://registry.npmjs.org"
-
-      - name: Install latest npm
-        run: |
-          npm install -g npm@latest
-
-      - name: Install Dependencies
-        run: |
-          npm ci
-
-      - name: Prepare package
-        run: |
-          npm run prepublishOnly
-        env:
-          TYPE_GRAPHQL_REF: ${{ github.ref_name }}
-
-      - name: Build Changelog
-        id: changelog
-        uses: mikepenz/release-changelog-builder-action@v4
-        with:
-          configuration: "./.github/configs/changelog.json"
-          owner: MichalLytek
-          repo: type-graphql
-          failOnError: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Release
-        uses: softprops/action-gh-release@v1
-        with:
-          body: ${{ steps.changelog.outputs.changelog }}
-          prerelease: ${{ steps.prerelease.outputs.value == 'true' }}
-
-      - name: Publish
-        run: |
-          _tag=
-          if [ "${{ steps.prerelease.outputs.value }}" = "true" ]; then
-            _tag="next"
-          else
-            _tag="latest"
-          fi
-
-          npm publish --ignore-scripts --tag "$_tag"
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-
-  website:
-    name: Publish website
-    needs: check
-    if: always() && github.ref == 'refs/heads/master'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: "18.x"
-
-      - name: Install Dependencies
-        run: |
-          npm ci
-          npm ci --prefix ./website
-
-      - name: Build
-        run: |
-          npm run build --prefix ./website
-
-      - name: Publish
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./website/build/type-graphql
-          user_name: "github-actions[bot]"
-          user_email: "github-actions[bot]@users.noreply.github.com"
-          full_commit_message: |
-            Deploy website based on ${{ github.sha }}
