chore: better regex v2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - master
     tags:
-      - v*
+      - ^v*
   pull_request:
     branches:
       - master
@@ -24,6 +24,15 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
+      - name: Check Git tag format
+        run: |
+          _tag="${{ github.ref_name }}"
+
+          if ! printf "%s\n" "$_tag" | grep -q -P '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$'; then
+            printf '[ERROR]: Git tag (%s) wrong format\n' "$_tag"
+            exit 1
+          fi
 
       - name: Read package.json version
         uses: sergeysova/jq-action@v2
