fix:(ci): workflows that depends on another workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,26 +10,42 @@ on:
       - master
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
+  group: ${{ github.workflow }}
   cancel-in-progress: true
 
 jobs:
   release:
     name: Release package on NPM
     runs-on: ubuntu-latest
-    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.ref_name, 'v')
+    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'refs/tags/v')
     permissions:
       contents: write
       id-token: write
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.workflow_run.head_branch }}
 
       - name: Read package.json version
         uses: sergeysova/jq-action@v2
         id: version
         with:
           cmd: jq --raw-output .version package.json
+
+      - name: Read Git tag version
+        id: tag
+        run: |
+          _ref="${{ github.event.workflow_run.head_branch }}"
+          printf 'value=%s\n' "${_ref#refs/tags/}" >> "$GITHUB_OUTPUT"
+
+      - name: Check package.json == Git tag
+        run: |
+          _version="v${{ steps.version.outputs.value }}"
+          if [ ! "$_version" = "${{ steps.tag.outputs.value }}" ]; then
+            printf '[ERROR]: package.json (%s) != Git tag (%s)\n' "$_version" "${{ steps.tag.outputs.value }}"
+            exit 1
+          fi
 
       - name: Determine if version is prerelease
         id: prerelease
@@ -61,7 +77,7 @@ jobs:
         run: |
           npm run prepublishOnly
         env:
-          TYPE_GRAPHQL_REF: ${{ github.ref_name }}
+          TYPE_GRAPHQL_REF: ${{ steps.tag.outputs.value }}
 
       - name: Build Changelog
         id: changelog
